apiVersion: v1
kind: Namespace
metadata:
  name: supabase
---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-auth
  namespace: supabase
type: Opaque
data:
  # Default development credentials - should be changed in production
  JWT_SECRET: $(echo -n "your-super-secret-jwt-token-with-at-least-32-characters" | base64)
  ANON_KEY: $(echo -n "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiJ9.lb5Wx9CQK8yqH-afu3P_9hKkXtYHJm_YJ2E-AT7h_x8" | base64)
  SERVICE_ROLE_KEY: $(echo -n "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIn0.M2d2z4SFn5C7HlJG8Bh1PdYTL9tLMqm9T5r1nrwwwvs" | base64)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-config
  namespace: supabase
data:
  POSTGRES_DB: postgres
  POSTGRES_PORT: "5432"
  API_PORT: "8000"
  STUDIO_PORT: "3000"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: supabase
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: supabase/postgres:14.1.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: supabase-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          value: "your-secure-password"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: supabase
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotrue
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotrue
  template:
    metadata:
      labels:
        app: gotrue
    spec:
      containers:
      - name: gotrue
        image: supabase/gotrue:v2.10.0
        ports:
        - containerPort: 9999
        env:
        - name: GOTRUE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-auth
              key: JWT_SECRET
        - name: GOTRUE_DB_DRIVER
          value: postgres
        - name: GOTRUE_API_HOST
          value: 0.0.0.0
        - name: GOTRUE_DB_HOST
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: gotrue
  namespace: supabase
spec:
  selector:
    app: gotrue
  ports:
  - port: 9999
    targetPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: rest
        image: postgrest/postgrest:v9.0.0
        ports:
        - containerPort: 3000
        env:
        - name: PGRST_DB_URI
          value: postgres://postgres:your-secure-password@postgres:5432/postgres
        - name: PGRST_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-auth
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: rest
  namespace: supabase
spec:
  selector:
    app: rest
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime
  namespace: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
      - name: realtime
        image: supabase/realtime:v0.22.4
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PASSWORD
          value: "your-secure-password"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-auth
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: realtime
  namespace: supabase
spec:
  selector:
    app: realtime
  ports:
  - port: 4000
    targetPort: 4000 